# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: experiment_development
  pool: 5
  username: cyncable
  password: cyncable
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: experiment_test
  pool: 5
  username: cyncable
  password: cyncable
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: experiment_production
  pool: 5
  username: cyncable
  password: cyncable
  host: localhost
